"""
Notebook Builder
=================
Programmatically builds well-structured Colab notebooks
for each phase of the competition pipeline.
"""

from __future__ import annotations

import json
from typing import Any


class NotebookBuilder:
    """
    Builds structured Colab notebooks from cells.
    Can generate .ipynb JSON or use Colab MCP to build live.
    """

    def __init__(self):
        self.cells: list[dict[str, Any]] = []

    def add_markdown(self, content: str) -> "NotebookBuilder":
        self.cells.append({
            "cell_type": "markdown",
            "source": content.split("\n"),
            "metadata": {},
        })
        return self

    def add_code(self, code: str, metadata: dict | None = None) -> "NotebookBuilder":
        self.cells.append({
            "cell_type": "code",
            "source": code.split("\n"),
            "metadata": metadata or {},
            "outputs": [],
            "execution_count": None,
        })
        return self

    def add_section(self, title: str, code: str, description: str = "") -> "NotebookBuilder":
        """Add a markdown header + optional description + code cell."""
        md = f"## {title}"
        if description:
            md += f"\n\n{description}"
        self.add_markdown(md)
        self.add_code(code)
        return self

    def build_eda_notebook(self, competition_slug: str, target_col: str = "") -> "NotebookBuilder":
        """Build a complete EDA notebook template."""
        self.add_markdown(f"# EDA: {competition_slug}\n\n*Auto-generated by AgenticCompete*")

        self.add_section(
            "1. Setup & Load Data",
            f"""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-whitegrid')

train = pd.read_csv('/content/data/train.csv')
test = pd.read_csv('/content/data/test.csv')
print(f"Train: {{train.shape}}, Test: {{test.shape}}")
train.head()""",
        )

        self.add_section("2. Data Overview", """
print("=== Data Types ===")
print(train.dtypes.value_counts())
print(f"\\n=== Memory Usage: {train.memory_usage(deep=True).sum() / 1e6:.1f} MB ===")
train.describe(include='all').T
""")

        self.add_section("3. Missing Values", """
missing = train.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(train) * 100).round(2)
missing_df = pd.DataFrame({'count': missing, 'pct': missing_pct})
missing_df = missing_df[missing_df['count'] > 0]
if len(missing_df) > 0:
    fig, ax = plt.subplots(figsize=(10, max(4, len(missing_df) * 0.3)))
    missing_df['pct'].plot(kind='barh', ax=ax)
    ax.set_title('Missing Values (%)')
    plt.tight_layout()
    plt.show()
else:
    print("No missing values!")
""")

        target = target_col or "target"
        self.add_section("4. Target Distribution", f"""
target_col = '{target}'
if target_col not in train.columns:
    target_col = train.columns[-1]

y = train[target_col]
print(f"Target: {{target_col}}, dtype: {{y.dtype}}, nunique: {{y.nunique()}}")

if y.nunique() <= 20:
    fig, ax = plt.subplots(figsize=(8, 4))
    y.value_counts().plot(kind='bar', ax=ax)
    ax.set_title(f'Target: {{target_col}}')
    plt.tight_layout()
    plt.show()
    print(f"Imbalance ratio: {{y.value_counts().max() / y.value_counts().min():.2f}}")
else:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    y.hist(bins=50, ax=axes[0])
    axes[0].set_title('Distribution')
    np.log1p(y).hist(bins=50, ax=axes[1])
    axes[1].set_title('Log Distribution')
    plt.tight_layout()
    plt.show()
    print(y.describe())
""")

        self.add_section("5. Feature Correlations", """
num_df = train.select_dtypes(include=['number'])
if len(num_df.columns) > 1:
    fig, ax = plt.subplots(figsize=(min(16, len(num_df.columns)), min(12, len(num_df.columns)*0.8)))
    corr = num_df.corr()
    sns.heatmap(corr, annot=len(corr) <= 15, fmt='.2f', cmap='RdBu_r', center=0, ax=ax)
    plt.title('Correlation Matrix')
    plt.tight_layout()
    plt.show()
""")

        self.add_section("6. Feature Importance (Quick RF)", f"""
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

target_col = '{target}' if '{target}' in train.columns else train.columns[-1]
X = train.select_dtypes(include=['number']).drop(columns=[target_col], errors='ignore').fillna(0)
y = train[target_col]

if y.dtype == 'object' or y.nunique() <= 20:
    le = LabelEncoder()
    y_enc = le.fit_transform(y.astype(str))
    rf = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42, n_jobs=-1)
    rf.fit(X, y_enc)
else:
    rf = RandomForestRegressor(n_estimators=100, max_depth=8, random_state=42, n_jobs=-1)
    rf.fit(X, y)

importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
fig, ax = plt.subplots(figsize=(10, max(4, min(20, len(importances)) * 0.3)))
importances.head(20).plot(kind='barh', ax=ax)
ax.set_title('Feature Importance (RF)')
plt.tight_layout()
plt.show()
""")

        return self

    def to_ipynb(self) -> dict:
        """Export as .ipynb JSON."""
        return {
            "nbformat": 4,
            "nbformat_minor": 0,
            "metadata": {
                "colab": {"provenance": [], "name": "AgenticCompete"},
                "kernelspec": {
                    "name": "python3",
                    "display_name": "Python 3",
                },
            },
            "cells": self.cells,
        }

    def save(self, path: str) -> None:
        """Save notebook to file."""
        with open(path, "w") as f:
            json.dump(self.to_ipynb(), f, indent=2)

    async def deploy_to_colab(self, session: Any) -> None:
        """Deploy all cells to a live Colab notebook via MCP."""
        for i, cell in enumerate(self.cells):
            if cell["cell_type"] == "markdown":
                content = "\n".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
                await session._call_mcp("add_text_cell", {
                    "cellIndex": i,
                    "content": content,
                })
            else:
                content = "\n".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
                await session._call_mcp("add_code_cell", {
                    "cellIndex": i,
                    "content": content,
                })
